import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import GlobalClientProviders from '@/common/providers/global-client-providers';
import Link from 'next/link';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();

	return (
		<html lang='en'>
			<body className={`${inter.className} bg-gray-100`}>
				<GlobalClientProviders>
					<nav className='h-[60px] flex items-center w-full justify-end'>
						<ul className='max-w-[1240px] mx-auto flex justify-end gap-4 w-full'>
							<li>
								<Link href={'/auth/signup'}>Register</Link>
							</li>
							<li>
								<Link href={'/auth/signin'}>Sign in</Link>
							</li>
							{session?.user && (
								<li>
									<Link href={'/profile'}>Profile</Link>
								</li>
							)}
						</ul>
					</nav>
					{children}
				</GlobalClientProviders>
			</body>
		</html>
	);
}
