import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import GlobalClientProviders from '@/common/providers/global-client-providers';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { Home } from 'lucide-react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();

	return (
		<html lang='en'>
			<body className={`${inter.className} bg-gray-100`}>
				<GlobalClientProviders>
					<nav className='h-[60px] flex items-center w-full justify-between'>
						<div className='max-w-[1240px] mx-auto flex justify-between w-full px-5'>
							<Link href={'/'} className='inline-flex items-center gap-1'>
								<Home className='size-5' />
								Home
							</Link>
							<ul className='max-w-[1240px] mx-auto flex justify-end gap-4 w-full'>
								{session?.user ? (
									<>
										<li>
											<Link href={'/api/auth/signout'}>Signout</Link>
										</li>
										<li>
											<Link href={'/profile'}>Profile</Link>
										</li>
									</>
								) : (
									<>
										<li>
											<Link href={'/auth/signup'}>Register</Link>
										</li>
										<li>
											<Link href={'/auth/signin'}>Sign in</Link>
										</li>
									</>
								)}
							</ul>
						</div>
					</nav>
					{children}
				</GlobalClientProviders>
			</body>
		</html>
	);
}
